### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by dickie-hrodebert** [theartful/polychase#9]
<img width="811" height="50" alt="Image" src="https://github.com/user-attachments/assets/50aa8517-2cd9-43d0-95aa-e9752001c1e0" />

**Comment by theartful** [comment]
@dickie-hrodebert Thanks for the bug report. Can you tell me more details on how to reproduce, or send the blend file?

**Comment by steveernst117** [comment]
I'm getting this same error too. It happens after clicking "Analyze Video". I tried it on a png sequence and an mp4 in Blender 4.5.6 and 5.0.1, same result everywhere. 

Thanks for your work on this! I can't wait to try it out!

**Comment by theartful** [comment]
@steveernst117 Can you send me a blend file with the video to reproduce the issue?

Sry, I'm not using the addon much currently, and I had little incentive to continuously polish it, hence these annoying bugs.

**Comment by steveernst117** [comment]
> [@steveernst117](https://github.com/steveernst117) Can you send me a blend file with the video to reproduce the issue?
> 
> Sry, I'm not using the addon much currently, and I had little incentive to continuously polish it, hence these annoying bugs.

It's the most basic of all blend files with the default cube and camera, I just selected a 4k sequence and all the other stuff and tried to analyze and that's the error I got.

**Comment by theartful** [comment]
@steveernst117 I would appreciate it still if you can provide the blend file and the 4k sequence (even if two images) just to reproduce.
It works fine with the data I test it with. I can't fix the issue if I can't reproduce it.

**Comment by steveernst117** [comment]
> [@steveernst117](https://github.com/steveernst117) I would appreciate it still if you can provide the blend file and the 4k sequence (even if two images) just to reproduce. It works fine with the data I test it with. I can't fix the issue if I can't reproduce it.

Well it looks like I get the first error when using a png sequence (converted from a portion of the mp4) and am getting a different error at the same point when using the original mp4:
Error: SQLite error [E:\Programming\polychase\cpp\database.cc:189]: constraint failed

4k footage used:
[https://www.pexels.com/video/aerial-view-of-a-church-in-a-small-town-27965658/](url)

Blend file:
[https://drive.google.com/file/d/1WMKU2PejpYsf-gOSEdwIzQXrKW07Swv5/view?usp=drive_link](url)

**Comment by theartful** [comment]
Thanks a lot, this is very helpful, I can reproduce the issue. I will fix it and get back to you.

**Comment by steveernst117** [comment]
Thank you so much!

**Comment by theartful** [comment]
@steveernst117 The issue with the clip you shared is that the first frame is black, which has no features. I'm handling this case incorrectly, and I'm pushing a new version soon. This is for the `constraint failed error`.

While I'm at it, I tried converting the video into a sequence of png files, but I can't reproduce the first error `rows != height`. Do you have an example for that case?

**Comment by theartful** [comment]
The issue should be solved in the new version.

**Comment by steveernst117** [comment]
> The issue should be solved in the new version.

Hey thanks for working on this!
I updated the extension, and it now works on the video file! But strangely, I still get the same error when using the png sequence. I wrote the sequence using Nuke and it has a bit depth of 48, resolution of 3840x2160. Not really sure what else to say, it should be pretty straightforward. In case it helps, here's the first 10 frames of my sequence:
[https://drive.google.com/file/d/10pNNRllsK7H1dqktnDaV-UEgcbTtkV21/view?usp=drive_link](url)

**Comment by theartful** [comment]
Should be fixed in the new version.

It was a funny bug. I expected image sequences to have only one numeric group, so that I would infer the image index from it, but this wasn't the case with the sequence you provided "church_drone_3840_2160_60fps_0001.png". This caused the sequence to start from 3840 instead of 1.

**Comment by steveernst117** [comment]
> Should be fixed in the new version.
> 
> It was a funny bug. I expected image sequences to have only one numeric group, so that I would infer the image index from it, but this wasn't the case with the sequence you provided "church_drone_3840_2160_60fps_0001.png". This caused the sequence to start from 3840 instead of 1.

Yep, looks like it works! Thanks so much for working on this addon, it's really impressive work!
